# Generated by Django 3.0.4 on 2020-03-17 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='information_block/static/img')),
                ('foto_id', models.IntegerField(default=1)),
                ('name_foto', models.TextField(default='enter short description here', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('short_information', models.TextField()),
                ('foto_logo', models.ImageField(upload_to='information_block/static/img')),
                ('hyper_link_site', models.TextField(default='http')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='future_conference_anonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20000)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('location', models.TextField(default='/')),
                ('link_facebook', models.TextField(default='Enter link here')),
                ('link_telegram', models.TextField(default='Enter link here')),
                ('link_twitter', models.TextField(default='Enter link here')),
                ('foto', models.ImageField(default='#', upload_to='information_block/static/img')),
                ('partner_id', models.ManyToManyField(to='information_block.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Enter title here')),
                ('image_head', models.ImageField(default='#', upload_to='information_block/static/img')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('link_facebook', models.TextField(default='Enter link here')),
                ('link_telegram', models.TextField(default='Enter link here')),
                ('link_twitter', models.TextField(default='Enter link here')),
                ('header_image', models.ManyToManyField(default=1, to='information_block.Foto_article')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
