# Generated by Django 3.0.4 on 2020-10-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('information_block', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='image_head',
        ),
        migrations.AlterField(
            model_name='articles',
            name='header_image',
            field=models.ManyToManyField(to='photologue.Photo'),
        ),
    ]
