# Generated by Django 3.0.4 on 2020-03-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_block', '0002_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='header_image',
            field=models.ManyToManyField(to='information_block.Foto_article'),
        ),
    ]
