# Generated by Django 3.0.4 on 2020-10-13 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('information_block', '0002_auto_20201013_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='image_head',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo'),
        ),
    ]
