# Generated by Django 3.0.4 on 2020-05-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_block', '0003_auto_20200323_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='image_head',
            field=models.ImageField(default='#', upload_to='information_block/static/img'),
        ),
    ]
