# Generated by Django 3.0.4 on 2020-10-13 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information_block', '0003_auto_20201013_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='future_conference_anonce',
            name='foto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
