# Generated by Django 3.0.4 on 2020-10-13 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('information_block', '0004_auto_20201013_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='future_conference_anonce',
            name='foto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo'),
        ),
    ]
