# Generated by Django 3.0.4 on 2020-10-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information_block', '0005_auto_20201013_2112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foto_article',
        ),
    ]
