# Generated by Django 3.0.4 on 2020-10-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information_block', '0007_articles_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='tags',
        ),
    ]
