# Generated by Django 3.0.4 on 2020-05-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_block', '0007_auto_20200520_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image_head',
            field=models.ImageField(default='#', upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='foto_article',
            name='foto',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
