# Generated by Django 3.0.4 on 2020-05-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_block', '0008_auto_20200520_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image_head',
            field=models.ImageField(default='#', upload_to=''),
        ),
    ]
