# Generated by Django 3.0.4 on 2020-05-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_block', '0010_auto_20200520_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_article',
            name='foto',
            field=models.ImageField(upload_to='media/img'),
        ),
    ]
