# Generated by Django 3.0.4 on 2020-05-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_block', '0012_auto_20200520_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='future_conference_anonce',
            name='foto',
            field=models.ImageField(default='#', upload_to=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='image_head',
            field=models.ImageField(default='#', upload_to=''),
        ),
        migrations.AlterField(
            model_name='partner',
            name='foto_logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
