# Generated by Django 3.0.4 on 2020-06-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_block', '0013_auto_20200522_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image_head',
            field=models.ImageField(default='#', upload_to='information_block/article'),
        ),
        migrations.AlterField(
            model_name='foto_article',
            name='foto',
            field=models.ImageField(upload_to='information_block/foto_article'),
        ),
        migrations.AlterField(
            model_name='future_conference_anonce',
            name='foto',
            field=models.ImageField(default='#', upload_to='information_block/conference'),
        ),
        migrations.AlterField(
            model_name='info',
            name='image_head',
            field=models.ImageField(default='#', upload_to='information_block/info'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='foto_logo',
            field=models.ImageField(upload_to='information_block/partner'),
        ),
    ]
