# Generated by Django 3.0.4 on 2020-10-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('information_block', '0014_auto_20200606_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='foto_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo'),
        ),
    ]
