# Generated by Django 3.0.4 on 2020-10-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information_block', '0015_partner_foto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='foto_id',
        ),
    ]
