# Generated by Django 3.0.4 on 2020-03-24 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entrance_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_code', models.IntegerField(default=103)),
            ],
        ),
        migrations.CreateModel(
            name='entrance_specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_name', models.TextField(default='enter specialization here')),
                ('foto', models.ImageField(default='#', upload_to='web/static/img')),
            ],
        ),
        migrations.CreateModel(
            name='entrance_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.TextField(default='enter subject here')),
                ('weigth_coef', models.FloatField(default=0.1)),
                ('min_grade', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='entrance_specialization_way',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_education', models.TextField(choices=[('Бакалавр', 'Бакалавр'), ('Магістр', 'Магістр'), ('Молодший спеціаліст', 'Молодший спеціаліст')], default='enter your form of education here', max_length=1000)),
                ('education_level', models.TextField(default='enter your education level here', max_length=1000)),
                ('license', models.IntegerField(default=1)),
                ('payment', models.IntegerField(default=1)),
                ('duration_of_study', models.FloatField(default=1.0)),
                ('short_description', models.TextField(default='Enter description here', max_length=100000)),
                ('code_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entrance.entrance_code')),
            ],
        ),
    ]
