# Generated by Django 3.0.4 on 2020-03-24 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        ('entrance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrance_specialization_way',
            name='edu_plan_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learning.edu_plan'),
        ),
        migrations.AddField(
            model_name='entrance_specialization_way',
            name='subject_id',
            field=models.ManyToManyField(to='entrance.entrance_subject'),
        ),
        migrations.AddField(
            model_name='entrance_code',
            name='specialization_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entrance.entrance_specialization'),
        ),
    ]
