# Generated by Django 3.0.4 on 2020-05-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0003_auto_20200519_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance_specialization',
            name='foto',
            field=models.ImageField(default='#', upload_to='information_block/static/img'),
        ),
    ]
