# Generated by Django 3.0.4 on 2020-05-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_edu_plan_specialization_name'),
        ('entrance', '0004_auto_20200519_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrance_specialization_way',
            name='edu_plan_id',
        ),
        migrations.AddField(
            model_name='entrance_specialization_way',
            name='edu_plan_id',
            field=models.ManyToManyField(default=1, to='learning.edu_plan'),
        ),
    ]
