# Generated by Django 3.0.4 on 2020-06-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_auto_20200606_1531'),
        ('entrance', '0006_auto_20200606_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance_specialization_way',
            name='code_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrance.entrance_code'),
        ),
        migrations.AlterField(
            model_name='entrance_specialization_way',
            name='edu_plan_id',
            field=models.ManyToManyField(to='learning.edu_plan'),
        ),
    ]
