# Generated by Django 3.0.4 on 2020-10-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0007_auto_20200606_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrance_specialization_way',
            name='form_education',
        ),
        migrations.AddField(
            model_name='entrance_specialization_way',
            name='education_form',
            field=models.TextField(choices=[('Денна', 'Денна'), ('Заочна', 'Заочна')], default='enter your education level here', max_length=1000),
        ),
        migrations.AddField(
            model_name='entrance_specialization_way',
            name='specialization_document',
            field=models.FileField(default='#', upload_to='entrance/docs'),
        ),
        migrations.AlterField(
            model_name='entrance_specialization_way',
            name='education_level',
            field=models.TextField(choices=[('Бакалавр', 'Бакалавр'), ('Магістр', 'Магістр'), ('Молодший спеціаліст', 'Молодший спеціаліст')], default='enter your form of education here', max_length=1000),
        ),
    ]
