# Generated by Django 3.0.4 on 2020-05-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20200524_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edu_plan',
            name='specialization_name',
            field=models.TextField(),
        ),
    ]
