# Generated by Django 3.0.4 on 2020-06-06 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0004_auto_20200524_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edu_plan',
            name='edu_plan_doc',
            field=models.FileField(upload_to='media/edu_plan/'),
        ),
        migrations.CreateModel(
            name='cathed_themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='media/cathed_themes')),
                ('document', models.FileField(upload_to='')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
