# Generated by Django 3.0.4 on 2020-06-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_auto_20200606_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathed_themes',
            name='name',
            field=models.TextField(default='cathed/themes'),
        ),
        migrations.AlterField(
            model_name='edu_plan',
            name='edu_plan_doc',
            field=models.FileField(upload_to='edu/plan/'),
        ),
    ]
