# Generated by Django 3.0.4 on 2020-03-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='stucture_cathed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cathed_name', models.TextField(max_length=50)),
                ('cathed_name_rus', models.TextField(default='write', max_length=100)),
                ('history', models.TextField()),
                ('foto', models.ImageField(upload_to='information_block/static/img')),
                ('number', models.CharField(max_length=25)),
                ('description', models.TextField(default='enter desciption here')),
                ('email', models.TextField(default='http')),
            ],
        ),
        migrations.CreateModel(
            name='structure_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.TextField(default='enter staff here')),
                ('permission_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='structure_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='name')),
                ('last_name', models.TextField(default='sername')),
                ('foto', models.ImageField(default='#', upload_to='information_block/static/img')),
                ('short_history', models.TextField(default='history')),
                ('phone_number', models.CharField(max_length=25)),
                ('monography', models.TextField(default='monography')),
                ('step', models.TextField(default='doctor')),
                ('cathed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.stucture_cathed')),
                ('staff_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='structure.structure_staff')),
            ],
        ),
    ]
