# Generated by Django 3.0.4 on 2020-06-06 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure_person',
            name='lab_staff',
            field=models.BooleanField(default=1),
        ),
        migrations.CreateModel(
            name='structure_laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.TextField(max_length=50)),
                ('lab_name_rus', models.TextField(default='write', max_length=100)),
                ('description', models.TextField(default='enter desciption here')),
                ('history', models.TextField()),
                ('foto', models.ImageField(upload_to='information_block/static/img')),
                ('number', models.CharField(max_length=25)),
                ('email', models.TextField(default='http')),
                ('adress', models.TextField(default='Kyiv')),
                ('cathed_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='structure.stucture_cathed')),
            ],
        ),
    ]
