# Generated by Django 3.0.4 on 2020-10-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_auto_20200606_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure_person',
            name='link_to_facebook',
            field=models.CharField(default='https', max_length=100),
        ),
        migrations.AddField(
            model_name='structure_person',
            name='middle_name',
            field=models.TextField(default='middlename'),
        ),
    ]
