# Generated by Django 3.0.4 on 2020-10-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_auto_20201004_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure_person',
            name='email',
            field=models.CharField(default='email@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='structure_person',
            name='link_to_twitter',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AlterField(
            model_name='structure_person',
            name='link_to_facebook',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
