# Generated by Django 3.0.4 on 2020-10-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_auto_20201004_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='stucture_cathed',
            name='foto_logo',
            field=models.ImageField(default='#', upload_to='structure/cathed'),
        ),
    ]
