# Generated by Django 3.0.4 on 2020-10-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_auto_20201004_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='stucture_cathed',
            name='science_edy',
            field=models.TextField(default='empty'),
        ),
    ]
