# Generated by Django 3.0.4 on 2020-10-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0009_stucture_cathed_science_edy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stucture_cathed',
            old_name='science_edy',
            new_name='science_edu',
        ),
    ]
