# Generated by Django 3.0.4 on 2020-10-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_auto_20201004_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure_laboratory',
            old_name='adress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='stucture_cathed',
            name='address',
            field=models.TextField(default='Kyiv'),
        ),
    ]
